// EduBD - Bangladesh Education Portal - Sample Data
const eduData = {
  lastUpdated: null,

  breakingNews: [
    "SSC পরীক্ষা ২০২৬: লিখিত পরীক্ষা ২১ এপ্রিল থেকে ২০ মে ২০২৬, ব্যবহারিক ০৭-১৪ জুন ২০২৬ — রুটিন: dhakaeducationboard.gov.bd",
    "HSC পরীক্ষা ২০২৬: এপ্রিল মাসে শুরু হয়েছে — রুটিন অনুযায়ী পরীক্ষা চলছে",
    "ঢাকা বিশ্ববিদ্যালয় ভর্তি ২০২৫-২৬: ফলাফল প্রকাশিত, ভর্তি চলছে",
    "জাতীয় বিশ্ববিদ্যালয়: অনার্স ১ম বর্ষ ভর্তি ২০২৫-২৬ — আবেদন শেষ তারিখ ৩০ এপ্রিল ২০২৬",
    "Chevening Scholarship 2026-27: বাংলাদেশী শিক্ষার্থীদের আবেদনের সুযোগ — শেষ তারিখ ৭ নভেম্বর ২০২৬",
    "মেডিকেল ভর্তি পরীক্ষা ২০২৫-২৬: চূড়ান্ত ফলাফল প্রকাশিত",
    "বুয়েট ভর্তি পরীক্ষা ২০২৫-২৬: মেধাতালিকা প্রকাশিত — ভর্তি কার্যক্রম চলছে",
    "একাদশ শ্রেণী ভর্তি ২০২৬: SSC ২০২৬ পাসকৃতদের জন্য অনলাইনে আবেদন শুরু হবে জুন ২০২৬-এ",
    "shed.gov.bd: মাধ্যমিক ও উচ্চ শিক্ষা বিভাগের সর্বশেষ নোটিশ ও বিজ্ঞপ্তি প্রকাশিত"
  ],

  latestNews: [
    {
      id: 0,
      category: "বোর্ড নোটিশ",
      title: "২০২৫ সালের (৭ম-১০ম) শ্রেণির বোর্ড পরিবর্তনকৃত শিক্ষার্থীদের ছাড়পত্রের অনুমতি পত্র (TN: 1021-1053)",
      summary: "ঢাকা শিক্ষা বোর্ড কর্তৃক ২০২৫ সালের ৭ম-১০ম শ্রেণির বোর্ড পরিবর্তনকৃত শিক্ষার্থীদের ছাড়পত্রের অনুমতি পত্র সংক্রান্ত বিজ্ঞপ্তি প্রকাশিত হয়েছে।",
      source: "ঢাকা শিক্ষা বোর্ড",
      date: "২০২৫",
      image: "",
      link: "https://dhakaeducationboard.portal.gov.bd/pages/notices/%E0%A7%A8%E0%A7%A6%E0%A7%A8%E0%A7%AB-%E0%A6%B8%E0%A6%BE%E0%A6%B2%E0%A7%87%E0%A6%B0-%E0%A7%AD%E0%A6%AE-%E0%A7%A7%E0%A7%A6%E0%A6%AE-%E0%A6%B6%E0%A7%8D%E0%A6%B0%E0%A7%87%E0%A6%A3%E0%A6%BF%E0%A6%B0-%E0%A6%AC%E0%A7%8B%E0%A6%B0%E0%A7%8D%E0%A6%A1-%E0%A6%AA%E0%A6%B0%E0%A6%BF%E0%A6%AC%E0%A6%B0%E0%A7%8D%E0%A6%A4%E0%A6%A8%E0%A6%95%E0%A7%83%E0%A6%A4-%E0%A6%B6%E0%A6%BF%E0%A6%95%E0%A7%8D%E0%A6%B7%E0%A6%BE%E0%A6%B0%E0%A7%8D%E0%A6%A5%E0%A7%80%E0%A6%A6%E0%A7%87%E0%A6%B0-e6edb0-6919990581fc96cef9e613d7",
      views: 0,
      year: "2025"
    },
    {
      id: 1,
      category: "SSC 2026",
      title: "SSC পরীক্ষা ২০২৬: লিখিত ২১ এপ্রিল — ২০ মে, ব্যবহারিক ০৭-১৪ জুন",
      summary: "SSC 2026 পরীক্ষার তারিখ অনুযায়ী ২০২৬ সালের এসএসসি লিখিত পরীক্ষা শুরু হবে ২১ এপ্রিল ২০২৬ থেকে এবং শেষ হবে ২০ মে ২০২৬ তারিখে। সকল লিখিত পরীক্ষা প্রতিদিন সকাল ১০টা থেকে নির্ধারিত কেন্দ্রগুলোতে অনুষ্ঠিত হবে। এছাড়া এসএসসি ব্যবহারিক পরীক্ষা অনুষ্ঠিত হবে ০৭ জুন থেকে ১৪ জুন ২০২৬ তারিখের মধ্যে।",
      source: "ঢাকা শিক্ষা বোর্ড",
      date: "২০২৬-০১-১৫",
      image: "",
      link: "pages/ssc.html",
      views: 19800,
      year: "2026"
    },
    {
      id: 2,
      category: "বিশ্ববিদ্যালয়",
      title: "ঢাকা বিশ্ববিদ্যালয় ভর্তি ২০২৫-২৬: মেধাতালিকা প্রকাশিত",
      summary: "ঢাকা বিশ্ববিদ্যালয়ের ২০২৫-২৬ শিক্ষাবর্ষের ভর্তি পরীক্ষার মেধাতালিকা প্রকাশিত হয়েছে। নির্বাচিত শিক্ষার্থীরা ভর্তির জন্য নির্ধারিত তারিখে রিপোর্ট করবেন।",
      source: "ঢাকা বিশ্ববিদ্যালয়",
      date: "২০২৬-০৩-১৫",
      image: "",
      link: "pages/admissions.html",
      views: 14500,
      year: "2026"
    },
    {
      id: 3,
      category: "স্কলারশিপ",
      title: "Chevening Scholarship 2026-27: আবেদন শুরু হয়েছে",
      summary: "যুক্তরাজ্য সরকারের Chevening বৃত্তি কর্মসূচিতে ২০২৬-২৭ শিক্ষাবর্ষে আবেদন শুরু হয়েছে। শেষ তারিখ ৭ নভেম্বর ২০২৬। এই বৃত্তিতে সম্পূর্ণ বিনামূল্যে যুক্তরাজ্যের বিশ্ববিদ্যালয়ে মাস্টার্স করার সুযোগ।",
      source: "British Council Bangladesh",
      date: "২০২৬-০৪-০১",
      image: "",
      link: "pages/scholarships.html",
      views: 11200,
      year: "2026"
    },
    {
      id: 4,
      category: "HSC 2026",
      title: "HSC পরীক্ষা ২০২৬: এপ্রিলে শুরু, নতুন প্রশ্নপত্র কাঠামো",
      summary: "উচ্চ মাধ্যমিক পরীক্ষা ২০২৬ এপ্রিল মাসে শুরু হয়েছে। নতুন পাঠ্যক্রম ও সৃজনশীল পদ্ধতিতে পরীক্ষা নেওয়া হচ্ছে। মোট ১৩ লাখ পরীক্ষার্থী অংশগ্রহণ করছে।",
      source: "আন্তঃশিক্ষা বোর্ড",
      date: "২০২৬-০৩-২০",
      image: "",
      link: "pages/hsc.html",
      views: 13400,
      year: "2026"
    },
    {
      id: 5,
      category: "মেডিকেল ভর্তি",
      title: "মেডিকেল ভর্তি পরীক্ষা ২০২৫-২৬: চূড়ান্ত ফলাফল প্রকাশ",
      summary: "সরকারি মেডিকেল কলেজে MBBS ভর্তির চূড়ান্ত ফলাফল প্রকাশিত হয়েছে। মোট ৫,৫৮০টি আসনে মেধাক্রম অনুযায়ী ভর্তি সম্পন্ন হচ্ছে।",
      source: "স্বাস্থ্য মন্ত্রণালয়",
      date: "২০২৬-০৩-১০",
      image: "",
      link: "pages/admissions.html",
      views: 9800,
      year: "2026"
    },
    {
      id: 6,
      category: "বৃত্তি",
      title: "সরকারি বৃত্তি ২০২৬: shed.gov.bd-তে আবেদন চলছে",
      summary: "মাধ্যমিক ও উচ্চ শিক্ষা বিভাগের মেধা বৃত্তি ও সাধারণ বৃত্তি ২০২৬-এর আবেদন চলছে। shed.gov.bd তে বিস্তারিত তথ্য পাওয়া যাচ্ছে।",
      source: "shed.gov.bd",
      date: "২০২৬-০৩-০১",
      image: "",
      link: "pages/scholarships.html",
      views: 9500,
      year: "2026"
    },
    {
      id: 7,
      category: "রুটিন",
      title: "SSC পরীক্ষা ২০২৬-এর চূড়ান্ত রুটিন প্রকাশিত — ঢাকা শিক্ষা বোর্ড",
      summary: "SSC পরীক্ষা ২০২৬-এর চূড়ান্ত রুটিন প্রকাশিত হয়েছে। লিখিত পরীক্ষা ২১ এপ্রিল ২০২৬ থেকে ২০ মে ২০২৬ পর্যন্ত এবং ব্যবহারিক পরীক্ষা ০৭ জুন থেকে ১৪ জুন ২০২৬ পর্যন্ত অনুষ্ঠিত হবে। প্রযোজ্য বোর্ড: ঢাকা, রাজশাহী, কুমিল্লা, যশোর, চট্টগ্রাম, বরিশাল, সিলেট, দিনাজপুর, ময়মনসিংহ।",
      source: "ঢাকা শিক্ষা বোর্ড",
      date: "২০২৬-০১-১৫",
      image: "",
      link: "pages/routines.html",
      views: 7800,
      year: "2026"
    },
    {
      id: 8,
      category: "বিদেশে পড়াশোনা",
      title: "DAAD Scholarship 2026-27: আবেদনের সুযোগ",
      summary: "জার্মান একাডেমিক এক্সচেঞ্জ সার্ভিস (DAAD) বাংলাদেশী শিক্ষার্থীদের জন্য ২০২৬-২৭ সেশনের বৃত্তি আবেদন গ্রহণ করছে। আবেদনের শেষ তারিখ অক্টোবর ২০২৬।",
      source: "DAAD Bangladesh",
      date: "২০২৬-০৪-০১",
      image: "",
      link: "pages/scholarships.html",
      views: 6300,
      year: "2026"
    },
    {
      id: 9,
      category: "কারিগরি",
      title: "কারিগরি শিক্ষা বোর্ডে ডিপ্লোমা ভর্তি ২০২৫-২৬",
      summary: "বাংলাদেশ কারিগরি শিক্ষা বোর্ডে ডিপ্লোমা ইন ইঞ্জিনিয়ারিং ২০২৫-২৬ সেশনে ভর্তি চলছে। অনলাইনে আবেদন করা যাচ্ছে।",
      source: "কারিগরি শিক্ষা বোর্ড",
      date: "২০২৬-০২-২০",
      image: "",
      link: "pages/news.html",
      views: 5100,
      year: "2026"
    },
    {
      id: 10,
      category: "মাদ্রাসা",
      title: "দাখিল পরীক্ষার রুটিন ২০২৬ প্রকাশিত",
      summary: "বাংলাদেশ মাদ্রাসা শিক্ষা বোর্ডের দাখিল পরীক্ষা ২০২৬-এর রুটিন প্রকাশিত হয়েছে। পরীক্ষা ফেব্রুয়ারি মাসে শুরু হয়েছে।",
      source: "মাদ্রাসা শিক্ষা বোর্ড",
      date: "২০২৬-০১-১০",
      image: "",
      link: "pages/news.html",
      views: 4600,
      year: "2026"
    },
    {
      id: 11,
      category: "নোটিশ",
      title: "জাতীয় বিশ্ববিদ্যালয়: অনার্স ১ম বর্ষ ভর্তি ২০২৫-২৬ বিজ্ঞপ্তি",
      summary: "জাতীয় বিশ্ববিদ্যালয়ের অনার্স ১ম বর্ষ ভর্তি ২০২৫-২৬ সেশনের বিজ্ঞপ্তি প্রকাশিত হয়েছে। অনলাইনে আবেদন চলছে — শেষ তারিখ ৩০ এপ্রিল ২০২৬।",
      source: "জাতীয় বিশ্ববিদ্যালয়",
      date: "২০২৬-০৪-০১",
      image: "",
      link: "pages/news.html",
      views: 7900,
      year: "2026"
    },
    {
      id: 12,
      category: "ফলাফল",
      title: "HSC ফলাফল ২০২৫: পাসের হার ৭৯.৫৩%",
      summary: "উচ্চ মাধ্যমিক সার্টিফিকেট (HSC) পরীক্ষার ফলাফল ২০২৫ প্রকাশিত হয়েছে। এবার মোট পাসের হার ৭৯.৫৩% এবং GPA-5 পেয়েছে ৯৮,১২৭ জন।",
      source: "আন্তঃশিক্ষা বোর্ড",
      date: "২০২৫-১১-২৬",
      image: "",
      link: "pages/results.html",
      views: 31200,
      year: "2025"
    },
    {
      id: 13,
      category: "ফলাফল",
      title: "SSC ফলাফল ২০২৫: পাসের হার ৮৩.০৪%",
      summary: "মাধ্যমিক সার্টিফিকেট (SSC) পরীক্ষার ফলাফল ২০২৫ প্রকাশিত হয়েছে। মোট পাসের হার ৮৩.০৪% এবং GPA-5 পেয়েছে ১,৩৮,৬৮৩ জন।",
      source: "আন্তঃশিক্ষা বোর্ড",
      date: "২০২৫-০৭-১২",
      image: "",
      link: "pages/results.html",
      views: 42000,
      year: "2025"
    },
    {
      id: 14,
      category: "ভর্তি",
      title: "একাদশ শ্রেণী ভর্তি ২০২৫: আবেদন শেষ হয়েছে",
      summary: "SSC ২০২৫ পাসকৃত শিক্ষার্থীদের একাদশ শ্রেণীতে ভর্তির আবেদন প্রক্রিয়া শেষ হয়েছে। ফলাফল ও ভর্তি কার্যক্রম সম্পন্ন।",
      source: "শিক্ষা মন্ত্রণালয়",
      date: "২০২৫-০৯-১৫",
      image: "",
      link: "pages/admissions.html",
      views: 18500,
      year: "2025"
    }
  ],

  admissions: [
    {
      id: 1,
      university: "ঢাকা বিশ্ববিদ্যালয়",
      type: "বিশ্ববিদ্যালয়",
      title: "ঢাকা বিশ্ববিদ্যালয় স্নাতক ভর্তি বিজ্ঞপ্তি ২০২৫-২৬",
      deadline: "2026-03-31",
      deadlineDisplay: "৩১ মার্চ ২০২৬",
      link: "https://admission.eis.du.ac.bd",
      status: "শেষ",
      seats: "৭,৩৯৬",
      fee: "৬৫০ টাকা",
      description: "ঢাকা বিশ্ববিদ্যালয়ের বিভিন্ন অনুষদে ২০২৫-২৬ শিক্ষাবর্ষে ভর্তির কার্যক্রম সম্পন্ন হয়েছে। মেধাতালিকা প্রকাশিত।",
      year: "2026"
    },
    {
      id: 2,
      university: "বুয়েট (BUET)",
      type: "ইঞ্জিনিয়ারিং",
      title: "BUET আন্ডারগ্রাজুয়েট ভর্তি ২০২৫-২৬",
      deadline: "2026-02-28",
      deadlineDisplay: "২৮ ফেব্রুয়ারি ২০২৬",
      link: "https://ugadmission.buet.ac.bd",
      status: "শেষ",
      seats: "১,১৫৫",
      fee: "৮৫০ টাকা",
      description: "বাংলাদেশ প্রকৌশল বিশ্ববিদ্যালয়ে ইঞ্জিনিয়ারিং, স্থাপত্য ও পরিকল্পনায় ভর্তির কার্যক্রম সম্পন্ন।",
      year: "2026"
    },
    {
      id: 3,
      university: "সরকারি মেডিকেল কলেজ",
      type: "মেডিকেল",
      title: "MBBS ভর্তি বিজ্ঞপ্তি ২০২৫-২৬",
      deadline: "2026-04-30",
      deadlineDisplay: "৩০ এপ্রিল ২০২৬",
      link: "https://dgme.gov.bd/pages/notices",
      status: "শেষ",
      seats: "৫,৫৮০",
      fee: "১,০০০ টাকা",
      description: "সরকারি মেডিকেল কলেজে MBBS ও BDS কোর্সে ভর্তির কার্যক্রম চলছে।",
      year: "2026"
    },
    {
      id: 4,
      university: "চট্টগ্রাম বিশ্ববিদ্যালয়",
      type: "বিশ্ববিদ্যালয়",
      title: "চট্টগ্রাম বিশ্ববিদ্যালয় ভর্তি ২০২৫-২৬",
      deadline: "2026-03-15",
      deadlineDisplay: "১৫ মার্চ ২০২৬",
      link: "https://admission.cu.ac.bd",
      status: "শেষ",
      seats: "৬,৫০০",
      fee: "৫৫০ টাকা",
      description: "চট্টগ্রাম বিশ্ববিদ্যালয়ের বিভিন্ন বিভাগে ২০২৫-২৬ ভর্তি সম্পন্ন।",
      year: "2026"
    },
    {
      id: 6,
      university: "রাজশাহী বিশ্ববিদ্যালয়",
      type: "বিশ্ববিদ্যালয়",
      title: "রাজশাহী বিশ্ববিদ্যালয় ভর্তি ২০২৫-২৬",
      deadline: "2026-03-20",
      deadlineDisplay: "২০ মার্চ ২০২৬",
      link: "https://admission.ru.ac.bd",
      status: "শেষ",
      seats: "৫,৮০০",
      fee: "৫০০ টাকা",
      description: "রাজশাহী বিশ্ববিদ্যালয়ে বিজ্ঞান, মানবিক ও বাণিজ্য অনুষদে ২০২৫-২৬ ভর্তি সম্পন্ন।",
      year: "2026"
    },
    {
      id: 7,
      university: "জাহাঙ্গীরনগর বিশ্ববিদ্যালয়",
      type: "বিশ্ববিদ্যালয়",
      title: "জাহাঙ্গীরনগর বিশ্ববিদ্যালয় ভর্তি ২০২৫-২৬",
      deadline: "2026-03-10",
      deadlineDisplay: "১০ মার্চ ২০২৬",
      link: "https://juniv.edu",
      status: "শেষ",
      seats: "২,৫০০",
      fee: "৬০০ টাকা",
      description: "জাহাঙ্গীরনগর বিশ্ববিদ্যালয়ের আন্ডারগ্র্যাজুয়েট প্রোগ্রামে ২০২৫-২৬ ভর্তি কার্যক্রম সম্পন্ন।",
      year: "2026"
    },
    {
      id: 8,
      university: "শাহজালাল বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
      type: "বিশ্ববিদ্যালয়",
      title: "SUST ভর্তি বিজ্ঞপ্তি ২০২৫-২৬",
      deadline: "2026-04-15",
      deadlineDisplay: "১৫ এপ্রিল ২০২৬",
      link: "https://www.sust.edu",
      status: "চলছে",
      seats: "১,৮০০",
      fee: "৫৫০ টাকা",
      description: "শাহজালাল বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়ে বিজ্ঞান ও প্রযুক্তি বিভাগে ভর্তি চলছে।",
      year: "2026"
    },
    {
      id: 9,
      university: "জাতীয় বিশ্ববিদ্যালয়",
      type: "বিশ্ববিদ্যালয়",
      title: "জাতীয় বিশ্ববিদ্যালয় অনার্স ভর্তি ২০২৫-২৬",
      deadline: "2026-04-30",
      deadlineDisplay: "৩০ এপ্রিল ২০২৬",
      link: "https://www.nu.ac.bd",
      status: "চলছে",
      seats: "৫,০০,০০০+",
      fee: "২৫০ টাকা",
      description: "জাতীয় বিশ্ববিদ্যালয়ের অধীন কলেজসমূহে অনার্স ১ম বর্ষে ভর্তির আবেদন চলছে।",
      year: "2026"
    },
    {
      id: 10,
      university: "বেসরকারি মেডিকেল কলেজ",
      type: "মেডিকেল",
      title: "বেসরকারি মেডিকেল ও ডেন্টাল কলেজ ভর্তি ২০২৫-২৬",
      deadline: "2026-05-31",
      deadlineDisplay: "৩১ মে ২০২৬",
      link: "https://dgme.gov.bd/pages/notices",
      status: "শীঘ্রই",
      seats: "৬,৩৫৫",
      fee: "১,৫০০ টাকা",
      description: "দেশের বেসরকারি মেডিকেল ও ডেন্টাল কলেজে MBBS ও BDS কোর্সে ভর্তির বিজ্ঞপ্তি শীঘ্রই আসবে।",
      year: "2026"
    },
    {
      id: 11,
      university: "ঢাকা বিশ্ববিদ্যালয়",
      type: "বিশ্ববিদ্যালয়",
      title: "ঢাকা বিশ্ববিদ্যালয় স্নাতক ভর্তি ২০২৪-২৫ — শেষ হয়েছে",
      deadline: "2025-03-31",
      deadlineDisplay: "৩১ মার্চ ২০২৫",
      link: "https://admission.eis.du.ac.bd",
      status: "শেষ হয়েছে",
      seats: "৭,৩৯৬",
      fee: "৬৫০ টাকা",
      description: "ঢাকা বিশ্ববিদ্যালয়ের ২০২৪-২৫ শিক্ষাবর্ষের ভর্তি সম্পন্ন হয়েছে।",
      year: "2025"
    },
    {
      id: 12,
      university: "সরকারি মেডিকেল কলেজ",
      type: "মেডিকেল",
      title: "MBBS ভর্তি ২০২৪-২৫ — শেষ হয়েছে",
      deadline: "2025-04-30",
      deadlineDisplay: "৩০ এপ্রিল ২০২৫",
      link: "https://dgme.gov.bd/pages/notices",
      status: "শেষ হয়েছে",
      seats: "৫,৫৮০",
      fee: "১,০০০ টাকা",
      description: "সরকারি মেডিকেল কলেজে ২০২৪-২৫ শিক্ষাবর্ষের ভর্তি সম্পন্ন হয়েছে।",
      year: "2025"
    }
  ],

  scholarships: [
    {
      id: 1,
      name: "Chevening Scholarship 2026-27",
      country: "যুক্তরাজ্য",
      flag: "🇬🇧",
      type: "সম্পূর্ণ বৃত্তি",
      level: "মাস্টার্স",
      amount: "সম্পূর্ণ খরচ (টিউশন + £১,১৯৫+/মাস)",
      deadline: "2026-11-07",
      deadlineDisplay: "৭ নভেম্বর ২০২৬",
      eligibility: "স্নাতক ডিগ্রি, ২ বছরের কর্ম অভিজ্ঞতা",
      link: "https://www.chevening.org",
      description: "যুক্তরাজ্য সরকারের সবচেয়ে মর্যাদাপূর্ণ বৃত্তি কর্মসূচি। টিউশন ফি, জীবনযাত্রার ভাতা, বিমান টিকিট সহ সব খরচ বহন করা হয়। প্রতি বছর বাংলাদেশ থেকে প্রায় ১৫-২০ জন এই বৃত্তি পান।",
      benefits: ["টিউশন ফি সম্পূর্ণ মওকুফ", "মাসিক ভাতা £১,১৯৫+", "আগমন ও প্রস্থান বিমান টিকিট", "স্বাস্থ্য বীমা", "ভিসা ফি"],
      requirements: ["স্নাতক ডিগ্রি (যেকোনো বিষয়)", "ন্যূনতম ২ বছর কর্ম অভিজ্ঞতা", "IELTS ৬.৫+", "বয়সসীমা নেই"],
      applicationProcess: "অনলাইনে আবেদন → সাক্ষাৎকার → চূড়ান্ত নির্বাচন",
      numberOfAwards: "বাংলাদেশ থেকে ১৫-২০টি",
      duration: "১ বছর (মাস্টার্স)",
      website: "https://www.chevening.org",
      year: "2026"
    },
    {
      id: 2,
      name: "Commonwealth Scholarship 2026-27",
      country: "যুক্তরাজ্য",
      flag: "🇬🇧",
      type: "সম্পূর্ণ বৃত্তি",
      level: "মাস্টার্স/পিএইচডি",
      amount: "সম্পূর্ণ খরচ",
      deadline: "2026-10-15",
      deadlineDisplay: "১৫ অক্টোবর ২০২৬",
      eligibility: "স্নাতক/স্নাতকোত্তর ডিগ্রি, কমনওয়েলথ দেশের নাগরিক",
      link: "https://cscuk.fcdo.gov.uk",
      description: "কমনওয়েলথ স্কলারশিপ কমিশন কর্তৃক প্রদত্ত বৃত্তি। যুক্তরাজ্যে উচ্চতর গবেষণা ও মাস্টার্স প্রোগ্রামের সুযোগ। উন্নয়নশীল দেশের মেধাবী শিক্ষার্থীদের জন্য বিশেষভাবে ডিজাইন করা।",
      benefits: ["টিউশন ফি মওকুফ", "মাসিক ভাতা", "বিমান টিকিট", "থিসিস গ্রান্ট"],
      requirements: ["প্রথম শ্রেণির স্নাতক ডিগ্রি", "IELTS ৬.০+", "গবেষণা প্রস্তাব (পিএইচডির জন্য)"],
      applicationProcess: "UGC বাংলাদেশের মাধ্যমে মনোনয়ন",
      numberOfAwards: "বাংলাদেশ থেকে ১০-১৫টি",
      duration: "১-৩ বছর",
      website: "https://cscuk.fcdo.gov.uk",
      year: "2026"
    },
    {
      id: 3,
      name: "DAAD Scholarship 2026-27",
      country: "জার্মানি",
      flag: "🇩🇪",
      type: "সম্পূর্ণ বৃত্তি",
      level: "মাস্টার্স/পিএইচডি",
      amount: "€৯৩৪/মাস (মাস্টার্স), €১,৩৬৫/মাস (পিএইচডি)",
      deadline: "2026-10-31",
      deadlineDisplay: "৩১ অক্টোবর ২০২৬",
      eligibility: "স্নাতক/স্নাতকোত্তর ডিগ্রি, ভালো একাডেমিক রেকর্ড",
      link: "https://www.daad.de",
      description: "জার্মান একাডেমিক এক্সচেঞ্জ সার্ভিস (DAAD) কর্তৃক প্রদত্ত বিশ্বের অন্যতম বড় বৃত্তি প্রোগ্রাম। জার্মানির বিশ্বমানের বিশ্ববিদ্যালয়ে বিনামূল্যে পড়ার সুযোগ। বেশিরভাগ প্রোগ্রাম ইংরেজিতে পাওয়া যায়।",
      benefits: ["মাসিক ভাতা €৯৩৪-১,৩৬৫", "স্বাস্থ্য বীমা", "ভ্রমণ ভাতা", "জার্মান ভাষা কোর্স"],
      requirements: ["স্নাতক ডিগ্রি", "IELTS ৬.০+ অথবা TOEFL ৮০+", "গবেষণা প্রস্তাব"],
      applicationProcess: "DAAD পোর্টালে অনলাইন আবেদন",
      numberOfAwards: "৫০০০+ বৃত্তি প্রতি বছর",
      duration: "১-৩ বছর",
      website: "https://www.daad.de",
      year: "2026"
    },
    {
      id: 4,
      name: "Fulbright Scholarship 2026-27",
      country: "যুক্তরাষ্ট্র",
      flag: "🇺🇸",
      type: "সম্পূর্ণ বৃত্তি",
      level: "মাস্টার্স/পিএইচডি",
      amount: "সম্পূর্ণ খরচ",
      deadline: "2026-06-15",
      deadlineDisplay: "১৫ জুন ২০২৬",
      eligibility: "স্নাতক ডিগ্রি, GPA ৩.০+, TOEFL ৭৯+",
      link: "https://bd.usembassy.gov/fulbright",
      description: "মার্কিন সরকারের সবচেয়ে মর্যাদাপূর্ণ আন্তর্জাতিক বৃত্তি। যুক্তরাষ্ট্রের শীর্ষ বিশ্ববিদ্যালয়ে পড়ার সুযোগ। বার্ষিক বৃত্তির পরিমাণ ৩০,০০০+ ডলার।",
      benefits: ["টিউশন ফি সম্পূর্ণ", "মাসিক ভাতা", "বিমান টিকিট", "স্বাস্থ্য বীমা", "সেটেলমেন্ট ভাতা"],
      requirements: ["স্নাতক ডিগ্রি (GPA ৩.০+)", "TOEFL ৭৯+ অথবা IELTS ৬.৫+", "গবেষণা পরিকল্পনা", "রেফারেন্স লেটার"],
      applicationProcess: "USEF Bangladesh-এর মাধ্যমে আবেদন",
      numberOfAwards: "বাংলাদেশ থেকে ৫-১০টি",
      duration: "১-২ বছর",
      website: "https://bd.usembassy.gov/fulbright",
      year: "2026"
    },
    {
      id: 5,
      name: "MEXT Scholarship 2026",
      country: "জাপান",
      flag: "🇯🇵",
      type: "সম্পূর্ণ বৃত্তি",
      level: "স্নাতক/মাস্টার্স/পিএইচডি",
      amount: "¥১১৭,০০০-১৪৫,০০০/মাস",
      deadline: "2026-05-31",
      deadlineDisplay: "৩১ মে ২০২৬",
      eligibility: "HSC/স্নাতক পাস, বয়স ১৭-৩৪ বছর",
      link: "https://www.bd.emb-japan.go.jp",
      description: "জাপান সরকার (মেক্সট) কর্তৃক বাংলাদেশী শিক্ষার্থীদের জন্য সম্পূর্ণ বৃত্তি। টিউশন ফি, আবাসন, ভাতা সহ সব সুবিধা প্রদান করা হয়। জাপানে প্রযুক্তি, বিজ্ঞান ও অন্যান্য বিষয়ে পড়ার সুযোগ।",
      benefits: ["টিউশন ফি সম্পূর্ণ মওকুফ", "মাসিক ভাতা ¥১১৭,০০০+", "বিমান টিকিট", "আবাসন সুবিধা"],
      requirements: ["HSC পাস (স্নাতকের জন্য)", "বয়স ১৭-২৫ বছর", "ভালো একাডেমিক রেকর্ড"],
      applicationProcess: "জাপান দূতাবাস ঢাকার মাধ্যমে আবেদন",
      numberOfAwards: "৫০+ (বাংলাদেশ থেকে)",
      duration: "৫ বছর (স্নাতক), ৩ বছর (মাস্টার্স/পিএইচডি)",
      website: "https://www.bd.emb-japan.go.jp",
      year: "2026"
    },
    {
      id: 6,
      name: "CSC Scholarship 2026 (China)",
      country: "চীন",
      flag: "🇨🇳",
      type: "সম্পূর্ণ বৃত্তি",
      level: "স্নাতক/মাস্টার্স/পিএইচডি",
      amount: "CNY ২,৫০০-৩,৫০০/মাস",
      deadline: "2026-04-30",
      deadlineDisplay: "৩০ এপ্রিল ২০২৬",
      eligibility: "SSC/HSC/স্নাতক পাস, বয়স সীমা প্রযোজ্য",
      link: "https://www.campuschina.org",
      description: "চীন সরকার (CSC) কর্তৃক বাংলাদেশী শিক্ষার্থীদের জন্য বিশেষ বৃত্তি। চীনের শীর্ষ বিশ্ববিদ্যালয়গুলোতে পড়ার সুযোগ। প্রতি বছর বাংলাদেশ থেকে শত শত শিক্ষার্থী এই বৃত্তি পান।",
      benefits: ["টিউশন ফি মওকুফ", "মাসিক ভাতা", "আবাসন", "স্বাস্থ্য বীমা"],
      requirements: ["ভালো একাডেমিক রেকর্ড", "বয়স ১৮-৩৫ বছর", "মেডিকেল সার্টিফিকেট"],
      applicationProcess: "CSC পোর্টাল ও চীন দূতাবাসের মাধ্যমে",
      numberOfAwards: "বাংলাদেশ থেকে ১০০+",
      duration: "৪ বছর (স্নাতক), ২-৩ বছর (মাস্টার্স/পিএইচডি)",
      website: "https://www.campuschina.org",
      year: "2026"
    },
    {
      id: 7,
      name: "Türkiye Bursları 2026",
      country: "তুরস্ক",
      flag: "🇹🇷",
      type: "সম্পূর্ণ বৃত্তি",
      level: "স্নাতক/মাস্টার্স/পিএইচডি",
      amount: "₺৭০০-১,৭৫০/মাস",
      deadline: "2026-02-28",
      deadlineDisplay: "২৮ ফেব্রুয়ারি ২০২৬",
      eligibility: "HSC/স্নাতক পাস, বয়স সীমা প্রযোজ্য",
      link: "https://www.turkiyeburslari.gov.tr",
      description: "তুরস্ক সরকারের প্রেস্টিজিয়াস বৃত্তি প্রোগ্রাম। আবাসন, ভাতা, বিমান টিকিট, তুর্কি ভাষা কোর্স সহ বৃত্তি। তুরস্কের শীর্ষ বিশ্ববিদ্যালয়গুলোতে পড়ার সুযোগ।",
      benefits: ["টিউশন ফি মওকুফ", "মাসিক ভাতা", "আবাসন", "বিমান টিকিট", "তুর্কি ভাষা কোর্স", "স্বাস্থ্য বীমা"],
      requirements: ["HSC পাস (স্নাতকের জন্য)", "GPA ৭০%+", "বয়স ১৮-২১ (স্নাতক)"],
      applicationProcess: "turkiyeburslari.gov.tr পোর্টালে আবেদন",
      numberOfAwards: "বাংলাদেশ থেকে ৫০+",
      duration: "৪ বছর (স্নাতক), ২ বছর (মাস্টার্স)",
      website: "https://www.turkiyeburslari.gov.tr",
      year: "2026"
    },
    {
      id: 8,
      name: "Australia Awards Scholarship 2026",
      country: "অস্ট্রেলিয়া",
      flag: "🇦🇺",
      type: "সম্পূর্ণ বৃত্তি",
      level: "মাস্টার্স/পিএইচডি",
      amount: "সম্পূর্ণ খরচ (AUD ৩৫,০০০+/বছর)",
      deadline: "2026-04-30",
      deadlineDisplay: "৩০ এপ্রিল ২০২৬",
      eligibility: "স্নাতক ডিগ্রি, ২ বছর কর্ম অভিজ্ঞতা, IELTS ৬.৫+",
      link: "https://www.australiaawardsbangladesh.org",
      description: "অস্ট্রেলিয়া সরকারের প্রেস্টিজিয়াস বৃত্তি। অস্ট্রেলিয়ার বিশ্বমানের বিশ্ববিদ্যালয়ে মাস্টার্স/পিএইচডি করার সুযোগ। সম্পূর্ণ খরচ, মাসিক ভাতা ও স্বাস্থ্য বীমা সহ।",
      benefits: ["টিউশন ফি সম্পূর্ণ", "মাসিক ভাতা AUD ২,৫০০+", "বিমান টিকিট", "স্বাস্থ্য বীমা", "প্রি-কোর্স ইংরেজি"],
      requirements: ["স্নাতক ডিগ্রি", "ন্যূনতম ২ বছর কর্ম অভিজ্ঞতা", "IELTS ৬.৫+", "বাংলাদেশী নাগরিক"],
      applicationProcess: "অস্ট্রেলিয়া অ্যাওয়ার্ডস ওয়েবসাইটে আবেদন",
      numberOfAwards: "বাংলাদেশ থেকে ৩০-৪০টি",
      duration: "১-৪ বছর",
      website: "https://www.australiaawardsbangladesh.org",
      year: "2026"
    },
    {
      id: 9,
      name: "Korean Government Scholarship (GKS/KGSP) 2026",
      country: "দক্ষিণ কোরিয়া",
      flag: "🇰🇷",
      type: "সম্পূর্ণ বৃত্তি",
      level: "স্নাতক/মাস্টার্স/পিএইচডি",
      amount: "KRW ৯০০,০০০-১,২০০,০০০/মাস",
      deadline: "2026-03-31",
      deadlineDisplay: "৩১ মার্চ ২০২৬",
      eligibility: "HSC/স্নাতক পাস, GPA ২.৬৪+, বয়স সীমা প্রযোজ্য",
      link: "https://www.niied.go.kr/user/main.do",
      description: "দক্ষিণ কোরিয়া সরকারের বৃত্তি প্রোগ্রাম (NIIED)। কোরিয়ার শীর্ষ বিশ্ববিদ্যালয়ে পড়ার সুযোগ সহ কোরিয়ান ভাষা কোর্স।",
      benefits: ["টিউশন ফি মওকুফ", "মাসিক ভাতা", "আবাসন ভর্তুকি", "বিমান টিকিট", "কোরিয়ান ভাষা প্রশিক্ষণ"],
      requirements: ["GPA ২.৬৪/৪.০ বা সমতুল্য", "বয়স ১৮-২৫ (স্নাতক)", "স্বাস্থ্য সনদ"],
      applicationProcess: "বাংলাদেশ দূতাবাস কোরিয়া বা বিশ্ববিদ্যালয়ের মাধ্যমে",
      numberOfAwards: "বাংলাদেশ থেকে ২০+",
      duration: "৩ বছর (স্নাতক+কোরিয়ান), ২+১ বছর (মাস্টার্স)",
      website: "https://www.niied.go.kr",
      year: "2026"
    },
    {
      id: 10,
      name: "Swedish Institute Scholarship 2026",
      country: "সুইডেন",
      flag: "🇸🇪",
      type: "সম্পূর্ণ বৃত্তি",
      level: "মাস্টার্স",
      amount: "SEK ১১,০০০/মাস",
      deadline: "2026-02-10",
      deadlineDisplay: "১০ ফেব্রুয়ারি ২০২৬",
      eligibility: "স্নাতক ডিগ্রি, ২ বছর কর্ম অভিজ্ঞতা, IELTS ৬.৫+",
      link: "https://si.se/en/apply/scholarships",
      description: "সুইডিশ ইনস্টিটিউট কর্তৃক বাংলাদেশ সহ উন্নয়নশীল দেশের শিক্ষার্থীদের জন্য বৃত্তি। সুইডেনের বিশ্বমানের বিশ্ববিদ্যালয়ে পড়ার সুযোগ।",
      benefits: ["টিউশন ফি মওকুফ", "মাসিক ভাতা SEK ১১,০০০", "বিমান টিকিট", "স্বাস্থ্য বীমা"],
      requirements: ["স্নাতক ডিগ্রি", "২+ বছর কর্ম অভিজ্ঞতা", "IELTS ৬.৫+"],
      applicationProcess: "University Admissions Sweden-এর মাধ্যমে",
      numberOfAwards: "বাংলাদেশ থেকে ১০-১৫টি",
      duration: "১-২ বছর",
      website: "https://si.se/en/apply/scholarships",
      year: "2026"
    },
    {
      id: 11,
      name: "Holland Scholarship 2026",
      country: "নেদারল্যান্ডস",
      flag: "🇳🇱",
      type: "আংশিক বৃত্তি",
      level: "স্নাতক/মাস্টার্স",
      amount: "€৫,০০০ (এককালীন)",
      deadline: "2026-02-01",
      deadlineDisplay: "১ ফেব্রুয়ারি ২০২৬",
      eligibility: "নন-ইইউ দেশের নাগরিক, স্নাতক ডিগ্রি",
      link: "https://www.studyinholland.nl/finances/scholarships/holland-scholarship",
      description: "নেদারল্যান্ডস সরকার ও বিশ্ববিদ্যালয়গুলোর যৌথ বৃত্তি প্রোগ্রাম। ডাচ বিশ্ববিদ্যালয়ে আংশিক খরচ সহায়তা।",
      benefits: ["€৫,০০০ এককালীন অনুদান", "নেটওয়ার্কিং সুযোগ"],
      requirements: ["স্নাতক ডিগ্রি", "ভালো একাডেমিক রেকর্ড", "IELTS ৬.০+"],
      applicationProcess: "নির্দিষ্ট বিশ্ববিদ্যালয়ের মাধ্যমে আবেদন",
      numberOfAwards: "প্রতি বিশ্ববিদ্যালয় থেকে বিভিন্ন সংখ্যা",
      duration: "আংশিক সহায়তা",
      website: "https://www.studyinholland.nl",
      year: "2026"
    },
    {
      id: 12,
      name: "Stipendium Hungaricum 2026",
      country: "হাঙ্গেরি",
      flag: "🇭🇺",
      type: "সম্পূর্ণ বৃত্তি",
      level: "স্নাতক/মাস্টার্স/পিএইচডি",
      amount: "HUF ১৪৩,৮০০/মাস",
      deadline: "2026-01-15",
      deadlineDisplay: "১৫ জানুয়ারি ২০২৬",
      eligibility: "HSC/স্নাতক পাস, ভালো একাডেমিক রেকর্ড",
      link: "https://stipendiumhungaricum.hu",
      description: "হাঙ্গেরি সরকারের বৃত্তি প্রোগ্রাম। হাঙ্গেরির বিভিন্ন বিশ্ববিদ্যালয়ে পড়ার সুযোগ। টিউশন ফি, আবাসন, মাসিক ভাতা সহ।",
      benefits: ["টিউশন ফি মওকুফ", "মাসিক ভাতা", "ছাত্রাবাস বা আবাসন ভাতা", "স্বাস্থ্য বীমা"],
      requirements: ["HSC বা সমতুল্য", "ভালো একাডেমিক ফলাফল", "স্বাস্থ্য সনদ"],
      applicationProcess: "UGC বাংলাদেশ বা সরাসরি পোর্টালে আবেদন",
      numberOfAwards: "বাংলাদেশ থেকে ৫০+",
      duration: "৪ বছর (স্নাতক), ১-২ বছর (মাস্টার্স)",
      website: "https://stipendiumhungaricum.hu",
      year: "2026"
    },
    {
      id: 13,
      name: "Russian Government Scholarship 2026",
      country: "রাশিয়া",
      flag: "🇷🇺",
      type: "সম্পূর্ণ বৃত্তি",
      level: "স্নাতক/মাস্টার্স/পিএইচডি",
      amount: "RUB ১৫,০০০-২০,০০০/মাস",
      deadline: "2026-03-15",
      deadlineDisplay: "১৫ মার্চ ২০২৬",
      eligibility: "HSC/স্নাতক পাস",
      link: "https://russia.study/en",
      description: "রাশিয়া সরকার কর্তৃক বিদেশী শিক্ষার্থীদের জন্য বৃত্তি। রাশিয়ার বিশ্বমানের প্রযুক্তি ও বিজ্ঞান বিশ্ববিদ্যালয়ে পড়ার সুযোগ।",
      benefits: ["টিউশন ফি মওকুফ", "মাসিক ভাতা", "ছাত্রাবাস সুবিধা"],
      requirements: ["HSC পাস", "স্বাস্থ্য সনদ", "পুলিশ ক্লিয়ারেন্স"],
      applicationProcess: "রাশিয়ান দূতাবাস বা russia.study পোর্টালে",
      numberOfAwards: "বাংলাদেশ থেকে ১০০+",
      duration: "৪-৫ বছর (স্নাতক), ২ বছর (মাস্টার্স)",
      website: "https://russia.study/en",
      year: "2026"
    },
    {
      id: 14,
      name: "ADB-Japan Scholarship 2026",
      country: "এশিয়া-প্যাসিফিক",
      flag: "🌏",
      type: "সম্পূর্ণ বৃত্তি",
      level: "মাস্টার্স",
      amount: "সম্পূর্ণ খরচ",
      deadline: "2026-06-30",
      deadlineDisplay: "৩০ জুন ২০২৬",
      eligibility: "স্নাতক ডিগ্রি, ২ বছর কর্ম অভিজ্ঞতা, ইংরেজি দক্ষতা",
      link: "https://www.adb.org/work-with-us/careers/japan-scholarship-program",
      description: "এশিয়ান ডেভেলপমেন্ট ব্যাংক ও জাপান সরকারের যৌথ বৃত্তি। এশিয়া-প্যাসিফিক অঞ্চলের শীর্ষ বিশ্ববিদ্যালয়ে মাস্টার্সের সুযোগ।",
      benefits: ["টিউশন ফি মওকুফ", "মাসিক ভাতা", "বিমান টিকিট", "স্বাস্থ্য বীমা"],
      requirements: ["স্নাতক ডিগ্রি (৫+ বছর)", "২ বছর কর্ম অভিজ্ঞতা", "TOEFL/IELTS"],
      applicationProcess: "নির্দিষ্ট বিশ্ববিদ্যালয়ের মাধ্যমে আবেদন",
      numberOfAwards: "৩০০+ প্রতি বছর (সকল দেশ থেকে)",
      duration: "১-২ বছর",
      website: "https://www.adb.org/work-with-us/careers/japan-scholarship-program",
      year: "2026"
    },
    {
      id: 15,
      name: "Vanier Canada Graduate Scholarship 2026",
      country: "কানাডা",
      flag: "🇨🇦",
      type: "সম্পূর্ণ বৃত্তি",
      level: "পিএইচডি",
      amount: "CAD ৫০,০০০/বছর",
      deadline: "2026-11-01",
      deadlineDisplay: "১ নভেম্বর ২০২৬",
      eligibility: "মাস্টার্স ডিগ্রি, গবেষণা ক্ষমতা, নেতৃত্বের গুণ",
      link: "https://vanier.gc.ca",
      description: "কানাডা সরকারের শীর্ষ পিএইচডি বৃত্তি। ৩ বছর মেয়াদী এই বৃত্তিতে CAD ৫০,০০০/বছর প্রদান করা হয়। বিশ্বের সেরা গবেষকদের আকৃষ্ট করতে ডিজাইন করা।",
      benefits: ["CAD ৫০,০০০/বছর ৩ বছরের জন্য", "বিশ্বমানের গবেষণা সুযোগ"],
      requirements: ["মাস্টার্স ডিগ্রি", "শক্তিশালী গবেষণা প্রস্তাব", "নেতৃত্বের অভিজ্ঞতা"],
      applicationProcess: "কানাডিয়ান বিশ্ববিদ্যালয়ের মাধ্যমে মনোনয়ন",
      numberOfAwards: "১৬৬টি প্রতি বছর (আন্তর্জাতিক)",
      duration: "৩ বছর",
      website: "https://vanier.gc.ca",
      year: "2026"
    },
    {
      id: 16,
      name: "New Zealand Scholarship 2026",
      country: "নিউজিল্যান্ড",
      flag: "🇳🇿",
      type: "সম্পূর্ণ বৃত্তি",
      level: "মাস্টার্স/পিএইচডি",
      amount: "NZD ২২,৫০০/বছর",
      deadline: "2026-03-28",
      deadlineDisplay: "২৮ মার্চ ২০২৬",
      eligibility: "স্নাতক ডিগ্রি, কর্ম অভিজ্ঞতা, IELTS ৬.৫+",
      link: "https://www.mfat.govt.nz/en/aid-and-development/new-zealand-scholarships",
      description: "নিউজিল্যান্ড সরকারের বৃত্তি। বাংলাদেশ সহ উন্নয়নশীল দেশের নাগরিকদের জন্য। উন্নয়নমূলক বিষয়ে মাস্টার্স/পিএইচডি করার সুযোগ।",
      benefits: ["টিউশন ফি মওকুফ", "মাসিক ভাতা", "বিমান টিকিট", "স্বাস্থ্য বীমা"],
      requirements: ["স্নাতক ডিগ্রি", "IELTS ৬.৫+", "উন্নয়নে অবদানের প্রতিশ্রুতি"],
      applicationProcess: "NZ Scholarships অনলাইন পোর্টালে আবেদন",
      numberOfAwards: "বাংলাদেশ থেকে ৫-১০টি",
      duration: "১-৩ বছর",
      website: "https://www.mfat.govt.nz/en/aid-and-development/new-zealand-scholarships",
      year: "2026"
    },
    {
      id: 17,
      name: "ICCR Scholarship (India) 2026-27",
      country: "ভারত",
      flag: "🇮🇳",
      type: "সম্পূর্ণ বৃত্তি",
      level: "স্নাতক/মাস্টার্স/পিএইচডি",
      amount: "INR ৯,৮০০-১৪,৭০০/মাস",
      deadline: "2026-05-31",
      deadlineDisplay: "৩১ মে ২০২৬",
      eligibility: "HSC/স্নাতক পাস",
      link: "https://www.iccr.gov.in",
      description: "ভারতীয় সাংস্কৃতিক সম্পর্ক পরিষদ (ICCR) কর্তৃক বৃত্তি। ভারতের বিভিন্ন বিশ্ববিদ্যালয়ে পড়ার সুযোগ। বাংলাদেশ থেকে প্রতি বছর অনেক শিক্ষার্থী এই বৃত্তি পান।",
      benefits: ["টিউশন ফি মওকুফ", "মাসিক ভাতা", "আবাসন", "বই ভাতা"],
      requirements: ["HSC পাস (ভালো ফলাফল)", "স্বাস্থ্য সনদ"],
      applicationProcess: "ভারতীয় হাই কমিশন ঢাকার মাধ্যমে",
      numberOfAwards: "বাংলাদেশ থেকে ৫০+",
      duration: "৩-৫ বছর",
      website: "https://www.iccr.gov.in",
      year: "2026"
    },
    {
      id: 18,
      name: "Singapore Government Scholarship 2026",
      country: "সিঙ্গাপুর",
      flag: "🇸🇬",
      type: "সম্পূর্ণ বৃত্তি",
      level: "স্নাতক/মাস্টার্স",
      amount: "SGD ১,৩০০-২,০০০/মাস",
      deadline: "2026-06-30",
      deadlineDisplay: "৩০ জুন ২০২৬",
      eligibility: "উচ্চ মেধাবী, HSC/স্নাতক, ইংরেজি দক্ষতা",
      link: "https://www.moe.gov.sg/financial-matters/awards-scholarships",
      description: "সিঙ্গাপুর সরকার কর্তৃক মেধাবী আন্তর্জাতিক শিক্ষার্থীদের জন্য বৃত্তি। সিঙ্গাপুরের বিশ্বমানের বিশ্ববিদ্যালয়ে পড়ার সুযোগ।",
      benefits: ["টিউশন ফি সম্পূর্ণ", "মাসিক ভাতা", "আবাসন ভর্তুকি"],
      requirements: ["উচ্চ একাডেমিক অর্জন", "ইংরেজি দক্ষতা", "সাক্ষাৎকার"],
      applicationProcess: "সিঙ্গাপুরের বিশ্ববিদ্যালয়ের মাধ্যমে আবেদন",
      numberOfAwards: "সীমিত সংখ্যা",
      duration: "৩-৪ বছর",
      website: "https://www.moe.gov.sg",
      year: "2026"
    },
    {
      id: 19,
      name: "Malaysian Government Scholarship 2026",
      country: "মালয়েশিয়া",
      flag: "🇲🇾",
      type: "সম্পূর্ণ বৃত্তি",
      level: "স্নাতক/মাস্টার্স/পিএইচডি",
      amount: "MYR ১,৫০০-২,৫০০/মাস",
      deadline: "2026-05-15",
      deadlineDisplay: "১৫ মে ২০২৬",
      eligibility: "HSC/স্নাতক পাস, IELTS ৬.০+",
      link: "https://biasiswa.mohe.gov.my",
      description: "মালয়েশিয়া সরকারের উচ্চশিক্ষা বৃত্তি। মালয়েশিয়ার শীর্ষ বিশ্ববিদ্যালয়গুলোতে পড়ার সুযোগ।",
      benefits: ["টিউশন ফি মওকুফ", "মাসিক ভাতা", "আবাসন ভর্তুকি"],
      requirements: ["HSC বা স্নাতক ডিগ্রি", "IELTS ৬.০+", "ভালো একাডেমিক রেকর্ড"],
      applicationProcess: "মালয়েশিয়ান হাই কমিশন বা বিশ্ববিদ্যালয়ের মাধ্যমে",
      numberOfAwards: "সীমিত",
      duration: "৩-৪ বছর",
      website: "https://biasiswa.mohe.gov.my",
      year: "2026"
    },
    {
      id: 20,
      name: "মাধ্যমিক ও উচ্চ শিক্ষা বিভাগ - সরকারি বৃত্তি ২০২৬",
      country: "বাংলাদেশ",
      flag: "🇧🇩",
      type: "সরকারি বৃত্তি",
      level: "মাধ্যমিক/উচ্চমাধ্যমিক/স্নাতক/স্নাতকোত্তর",
      amount: "বিভিন্ন (সরকারি নির্ধারিত)",
      deadline: "2026-12-31",
      deadlineDisplay: "চলমান",
      eligibility: "সরকার নির্ধারিত যোগ্যতা অনুযায়ী",
      link: "https://shed.gov.bd/pages/moedu-scholarships",
      description: "মাধ্যমিক ও উচ্চ শিক্ষা বিভাগ কর্তৃক পরিচালিত সকল সরকারি বৃত্তি কর্মসূচি। SSC, HSC, স্নাতক ও স্নাতকোত্তর পর্যায়ে মেধা ও সাধারণ বৃত্তি প্রদান করা হয়।",
      benefits: ["মেধা বৃত্তি", "সাধারণ বৃত্তি", "উপবৃত্তি", "শিক্ষা সহায়তা"],
      requirements: ["বাংলাদেশী নাগরিক", "নির্ধারিত পরীক্ষায় উত্তীর্ণ", "আর্থিক প্রয়োজনীয়তা (কিছু ক্ষেত্রে)"],
      applicationProcess: "শিক্ষা প্রতিষ্ঠানের মাধ্যমে অনলাইনে আবেদন",
      numberOfAwards: "লক্ষাধিক প্রতি বছর",
      duration: "বার্ষিক নবায়নযোগ্য",
      website: "https://shed.gov.bd/pages/moedu-scholarships",
      year: "2026"
    },
    {
      id: 21,
      name: "মেধা বৃত্তি (SSC/HSC) ২০২৬ — shed.gov.bd",
      country: "বাংলাদেশ",
      flag: "🇧🇩",
      type: "সরকারি বৃত্তি",
      level: "মাধ্যমিক/উচ্চমাধ্যমিক",
      amount: "৩৫০-৮৮০ টাকা/মাস",
      deadline: "2026-09-30",
      deadlineDisplay: "৩০ সেপ্টেম্বর ২০২৬",
      eligibility: "SSC/HSC ২০২৬ পরীক্ষায় মেধা তালিকায় স্থান",
      link: "https://shed.gov.bd/pages/moedu-scholarships",
      description: "মাধ্যমিক ও উচ্চ শিক্ষা অধিদপ্তর কর্তৃক মেধা বৃত্তি প্রদান। SSC ও HSC পরীক্ষায় সর্বোচ্চ ফলাফলকারীদের জন্য।",
      benefits: ["মাসিক বৃত্তি ৩৫০-৮৮০ টাকা", "শিক্ষা উপকরণ ভাতা"],
      requirements: ["SSC/HSC পরীক্ষায় মেধা তালিকায় স্থান", "নিয়মিত ছাত্র/ছাত্রী"],
      applicationProcess: "শিক্ষা বোর্ডের মাধ্যমে স্বয়ংক্রিয় নির্বাচন",
      numberOfAwards: "হাজার হাজার প্রতি বছর",
      duration: "২ বছর",
      website: "https://shed.gov.bd/pages/moedu-scholarships",
      year: "2026"
    },
    {
      id: 22,
      name: "উপবৃত্তি কর্মসূচি ২০২৫-২৬",
      country: "বাংলাদেশ",
      flag: "🇧🇩",
      type: "সরকারি বৃত্তি",
      level: "মাধ্যমিক/উচ্চমাধ্যমিক",
      amount: "১০০-৩৫০ টাকা/মাস",
      deadline: "2026-08-31",
      deadlineDisplay: "৩১ আগস্ট ২০২৬",
      eligibility: "আর্থিকভাবে অসচ্ছল পরিবারের ছাত্রছাত্রী",
      link: "https://shed.gov.bd/pages/moedu-scholarships",
      description: "মাধ্যমিক ও উচ্চ মাধ্যমিক পর্যায়ের দরিদ্র শিক্ষার্থীদের শিক্ষা অব্যাহত রাখতে উপবৃত্তি প্রদান করা হয়।",
      benefits: ["মাসিক উপবৃত্তি", "পাঠ্যবই ভাতা", "পরীক্ষার ফি ছাড়"],
      requirements: ["নিম্ন আয়ের পরিবার", "নিয়মিত উপস্থিতি ৭৫%+", "উত্তীর্ণ ছাত্রছাত্রী"],
      applicationProcess: "শিক্ষা প্রতিষ্ঠানের মাধ্যমে আবেদন",
      numberOfAwards: "লক্ষাধিক প্রতি বছর",
      duration: "শিক্ষাকালীন মেয়াদ",
      website: "https://shed.gov.bd/pages/moedu-scholarships",
      year: "2026"
    },
    {
      id: 23,
      name: "প্রধানমন্ত্রী শিক্ষা সহায়তা ট্রাস্ট ২০২৬",
      country: "বাংলাদেশ",
      flag: "🇧🇩",
      type: "আংশিক বৃত্তি",
      level: "এসএসসি/এইচএসসি/স্নাতক",
      amount: "৫,০০০-৬০,০০০ টাকা/বছর",
      deadline: "2026-06-30",
      deadlineDisplay: "৩০ জুন ২০২৬",
      eligibility: "মেধাবী ও আর্থিকভাবে অসচ্ছল শিক্ষার্থী",
      link: "https://pmeat.gov.bd",
      description: "প্রধানমন্ত্রীর শিক্ষা সহায়তা ট্রাস্ট থেকে মেধাবী ও দরিদ্র শিক্ষার্থীদের বৃত্তি প্রদান করা হয়। ২০২৬ সালে বৃত্তির পরিমাণ বৃদ্ধি করা হয়েছে।",
      benefits: ["বার্ষিক আর্থিক সহায়তা", "উচ্চশিক্ষায় অগ্রাধিকার"],
      requirements: ["SSC/HSC-তে GPA ৩.৫+", "পারিবারিক আয় নির্দিষ্ট সীমার মধ্যে", "নিয়মিত ছাত্র"],
      applicationProcess: "শিক্ষা প্রতিষ্ঠানের মাধ্যমে অনলাইনে আবেদন",
      numberOfAwards: "লক্ষাধিক",
      duration: "বার্ষিক নবায়নযোগ্য",
      website: "https://pmeat.gov.bd",
      year: "2026"
    },
    {
      id: 24,
      name: "UGC বৃত্তি ২০২৫-২৬",
      country: "বাংলাদেশ",
      flag: "🇧🇩",
      type: "আংশিক বৃত্তি",
      level: "স্নাতক/মাস্টার্স/পিএইচডি",
      amount: "৩,০০০-২০,০০০ টাকা/মাস",
      deadline: "2026-08-31",
      deadlineDisplay: "৩১ আগস্ট ২০২৬",
      eligibility: "পাবলিক বিশ্ববিদ্যালয়ের মেধাবী শিক্ষার্থী",
      link: "https://ugc.gov.bd",
      description: "বিশ্ববিদ্যালয় মঞ্জুরি কমিশন (UGC) কর্তৃক পাবলিক বিশ্ববিদ্যালয়ের মেধাবী শিক্ষার্থী ও গবেষকদের বৃত্তি।",
      benefits: ["মাসিক বৃত্তি", "গবেষণা অনুদান (পিএইচডির জন্য)"],
      requirements: ["পাবলিক বিশ্ববিদ্যালয়ের শিক্ষার্থী", "CGPA ৩.৫+", "নিয়মিত ছাত্র/ছাত্রী"],
      applicationProcess: "বিশ্ববিদ্যালয়ের রেজিস্ট্রার অফিসের মাধ্যমে",
      numberOfAwards: "বিশ্ববিদ্যালয় অনুযায়ী ভিন্ন",
      duration: "বার্ষিক নবায়নযোগ্য",
      website: "https://ugc.gov.bd",
      year: "2026"
    },
    {
      id: 25,
      name: "সরকারি বৃত্তি (SSC/HSC) ২০২৪-২৫ — শেষ হয়েছে",
      country: "বাংলাদেশ",
      flag: "🇧🇩",
      type: "সরকারি বৃত্তি",
      level: "মাধ্যমিক/উচ্চমাধ্যমিক",
      amount: "৩৫০-৮৮০ টাকা/মাস",
      deadline: "2025-09-30",
      deadlineDisplay: "৩০ সেপ্টেম্বর ২০২৫",
      eligibility: "SSC/HSC ২০২৫ পরীক্ষায় মেধা তালিকায় স্থান",
      link: "https://shed.gov.bd",
      description: "২০২৪-২৫ শিক্ষাবর্ষের সরকারি বৃত্তি — প্রদান সম্পন্ন হয়েছে।",
      benefits: ["মাসিক বৃত্তি", "শিক্ষা উপকরণ ভাতা"],
      requirements: ["SSC/HSC পরীক্ষায় মেধা তালিকায় স্থান"],
      applicationProcess: "শিক্ষা বোর্ডের মাধ্যমে",
      numberOfAwards: "হাজার হাজার",
      duration: "২ বছর",
      website: "https://shed.gov.bd",
      year: "2025"
    }
  ],


  deadlines: [
    { id: 1, title: "SUST ভর্তি আবেদন শেষ", date: "2026-04-15", link: "pages/admissions.html", year: "2026" },
    { id: 2, title: "জাতীয় বিশ্ববিদ্যালয় অনার্স ভর্তি শেষ", date: "2026-04-30", link: "pages/admissions.html", year: "2026" },
    { id: 3, title: "মেডিকেল ভর্তি শেষ তারিখ", date: "2026-04-30", link: "pages/admissions.html", year: "2026" },
    { id: 4, title: "CSC বৃত্তি (চীন) শেষ তারিখ", date: "2026-04-30", link: "pages/scholarships.html", year: "2026" },
    { id: 11, title: "SSC পরীক্ষা শুরু (লিখিত)", date: "2026-04-21", link: "pages/ssc.html", year: "2026" },
    { id: 5, title: "Fulbright বৃত্তি শেষ তারিখ", date: "2026-06-15", link: "pages/scholarships.html", year: "2026" },
    { id: 6, title: "HSC পরীক্ষা শুরু", date: "2026-04-02", link: "pages/hsc.html", year: "2026" },
    { id: 12, title: "SSC পরীক্ষা শেষ (লিখিত)", date: "2026-05-20", link: "pages/ssc.html", year: "2026" },
    { id: 7, title: "MEXT (জাপান) বৃত্তি শেষ তারিখ", date: "2026-05-31", link: "pages/scholarships.html", year: "2026" },
    { id: 13, title: "SSC ব্যবহারিক পরীক্ষা শুরু", date: "2026-06-07", link: "pages/ssc.html", year: "2026" },
    { id: 14, title: "SSC ব্যবহারিক পরীক্ষা শেষ", date: "2026-06-14", link: "pages/ssc.html", year: "2026" },
    { id: 8, title: "একাদশ শ্রেণী ভর্তি শুরু", date: "2026-06-15", link: "pages/admissions.html", year: "2026" },
    { id: 9, title: "Chevening বৃত্তি শেষ তারিখ ২০২৬-২৭", date: "2026-11-07", link: "pages/scholarships.html", year: "2026" },
    { id: 10, title: "DAAD বৃত্তি শেষ তারিখ ২০২৬-২৭", date: "2026-10-31", link: "pages/scholarships.html", year: "2026" }
  ],

  boards: [
    {
      id: "dhaka",
      name: "ঢাকা শিক্ষা বোর্ড",
      shortName: "ঢাকা",
      website: "https://dhakaeducationboard.portal.gov.bd",
      phone: "০২-৯৫৫৮৬৩৫",
      email: "info@dhakaeducationboard.gov.bd",
      address: "বাংলাদেশ সরকার, মাধ্যমিক ও উচ্চ মাধ্যমিক শিক্ষা বোর্ড, ঢাকা",
      established: "১৯২১",
      districts: ["ঢাকা", "ময়মনসিংহ", "গাজীপুর", "নারায়ণগঞ্জ", "মুন্সীগঞ্জ", "মানিকগঞ্জ", "কিশোরগঞ্জ"],
      pdfLinks: [
        { title: "২০২৫ সালের (৭ম-১০ম) শ্রেণির বোর্ড পরিবর্তনকৃত শিক্ষার্থীদের ছাড়পত্রের অনুমতি পত্র (TN: 1021-1053)", url: "https://dhakaeducationboard.portal.gov.bd/pages/notices/%E0%A7%A8%E0%A7%A6%E0%A7%A8%E0%A7%AB-%E0%A6%B8%E0%A6%BE%E0%A6%B2%E0%A7%87%E0%A6%B0-%E0%A7%AD%E0%A6%AE-%E0%A7%A7%E0%A7%A6%E0%A6%AE-%E0%A6%B6%E0%A7%8D%E0%A6%B0%E0%A7%87%E0%A6%A3%E0%A6%BF%E0%A6%B0-%E0%A6%AC%E0%A7%8B%E0%A6%B0%E0%A7%8D%E0%A6%A1-%E0%A6%AA%E0%A6%B0%E0%A6%BF%E0%A6%AC%E0%A6%B0%E0%A7%8D%E0%A6%A4%E0%A6%A8%E0%A6%95%E0%A7%83%E0%A6%A4-%E0%A6%B6%E0%A6%BF%E0%A6%95%E0%A7%8D%E0%A6%B7%E0%A6%BE%E0%A6%B0%E0%A7%8D%E0%A6%A5%E0%A7%80%E0%A6%A6%E0%A7%87%E0%A6%B0-e6edb0-6919990581fc96cef9e613d7" },
        { title: "SSC রুটিন ২০২৬", url: "https://dhakaeducationboard.gov.bd/data/20260115170804251115.pdf" }
      ]
    },
    {
      id: "rajshahi",
      name: "রাজশাহী শিক্ষা বোর্ড",
      shortName: "রাজশাহী",
      website: "https://rajshahieducationboard.gov.bd",
      phone: "০৭২১-৭৭৫৪৫৩",
      email: "info@rajshahieducationboard.gov.bd",
      address: "রাজশাহী, বাংলাদেশ",
      established: "১৯৬১",
      districts: ["রাজশাহী", "নওগাঁ", "নাটোর", "চাঁপাইনবাবগঞ্জ", "পাবনা", "সিরাজগঞ্জ", "বগুড়া", "জয়পুরহাট"],
      pdfLinks: [
        { title: "SSC রুটিন ২০২৬", url: "https://dhakaeducationboard.gov.bd/data/20260115170804251115.pdf" }
      ]
    },
    {
      id: "chittagong",
      name: "চট্টগ্রাম শিক্ষা বোর্ড",
      shortName: "চট্টগ্রাম",
      website: "https://bise-ctg.portal.gov.bd",
      phone: "০৩১-৬৩০৮৩০",
      email: "info@bise-ctg.gov.bd",
      address: "চট্টগ্রাম, বাংলাদেশ",
      established: "১৯৯৫",
      districts: ["চট্টগ্রাম", "কক্সবাজার", "রাঙ্গামাটি", "বান্দরবান", "খাগড়াছড়ি"],
      pdfLinks: [
        { title: "SSC রুটিন ২০২৬", url: "https://dhakaeducationboard.gov.bd/data/20260115170804251115.pdf" }
      ]
    },
    {
      id: "sylhet",
      name: "সিলেট শিক্ষা বোর্ড",
      shortName: "সিলেট",
      website: "https://sylheteducationboard.gov.bd",
      phone: "০৮২১-৭১৬৯৮৪",
      email: "info@sylheteducationboard.gov.bd",
      address: "সিলেট, বাংলাদেশ",
      established: "১৯৯৯",
      districts: ["সিলেট", "সুনামগঞ্জ", "হবিগঞ্জ", "মৌলভীবাজার"],
      pdfLinks: [
        { title: "SSC রুটিন ২০২৬", url: "https://dhakaeducationboard.gov.bd/data/20260115170804251115.pdf" }
      ]
    },
    {
      id: "comilla",
      name: "কুমিল্লা শিক্ষা বোর্ড",
      shortName: "কুমিল্লা",
      website: "https://comillaboard.portal.gov.bd",
      phone: "০৮১-৭৮০০৬২",
      email: "info@comillaboard.gov.bd",
      address: "কুমিল্লা, বাংলাদেশ",
      established: "১৯৬২",
      districts: ["কুমিল্লা", "ফেনী", "চাঁদপুর", "ব্রাহ্মণবাড়িয়া", "নোয়াখালী", "লক্ষ্মীপুর"],
      pdfLinks: [
        { title: "SSC রুটিন ২০২৬", url: "https://dhakaeducationboard.gov.bd/data/20260115170804251115.pdf" }
      ]
    },
    {
      id: "barisal",
      name: "বরিশাল শিক্ষা বোর্ড",
      shortName: "বরিশাল",
      website: "https://barisalboard.portal.gov.bd",
      phone: "০৪৩১-৬২৪৪০",
      email: "info@barisalboard.gov.bd",
      address: "বরিশাল, বাংলাদেশ",
      established: "১৯৯৯",
      districts: ["বরিশাল", "পটুয়াখালী", "পিরোজপুর", "ঝালকাঠি", "ভোলা", "বরগুনা"],
      pdfLinks: [
        { title: "SSC রুটিন ২০২৬", url: "https://dhakaeducationboard.gov.bd/data/20260115170804251115.pdf" }
      ]
    },
    {
      id: "jessore",
      name: "যশোর শিক্ষা বোর্ড",
      shortName: "যশোর",
      website: "https://jessoreboard.gov.bd",
      phone: "০৪২১-৬৫৫০৬",
      email: "info@jessoreboard.gov.bd",
      address: "যশোর, বাংলাদেশ",
      established: "১৯৬৩",
      districts: ["যশোর", "খুলনা", "বাগেরহাট", "সাতক্ষীরা", "নড়াইল", "মাগুরা", "ঝিনাইদহ", "কুষ্টিয়া", "মেহেরপুর", "চুয়াডাঙ্গা"],
      pdfLinks: [
        { title: "SSC রুটিন ২০২৬", url: "https://dhakaeducationboard.gov.bd/data/20260115170804251115.pdf" }
      ]
    },
    {
      id: "dinajpur",
      name: "দিনাজপুর শিক্ষা বোর্ড",
      shortName: "দিনাজপুর",
      website: "https://dinajpurboard.portal.gov.bd",
      phone: "০৫৩১-৬৩৭৩৯",
      email: "info@dinajpurboard.gov.bd",
      address: "দিনাজপুর, বাংলাদেশ",
      established: "১৯৬৩",
      districts: ["দিনাজপুর", "রংপুর", "কুড়িগ্রাম", "গাইবান্ধা", "নীলফামারী", "লালমনিরহাট", "ঠাকুরগাঁও", "পঞ্চগড়"],
      pdfLinks: [
        { title: "SSC রুটিন ২০২৬", url: "https://dhakaeducationboard.gov.bd/data/20260115170804251115.pdf" }
      ]
    },
    {
      id: "mymensingh",
      name: "ময়মনসিংহ শিক্ষা বোর্ড",
      shortName: "ময়মনসিংহ",
      website: "https://mymensingheducationboard.gov.bd",
      phone: "০৯১-৬৭০৩৮",
      email: "info@mymensingheducationboard.gov.bd",
      address: "ময়মনসিংহ, বাংলাদেশ",
      established: "২০১৭",
      districts: ["ময়মনসিংহ", "জামালপুর", "শেরপুর", "নেত্রকোণা"],
      pdfLinks: [
        { title: "SSC রুটিন ২০২৬", url: "https://dhakaeducationboard.gov.bd/data/20260115170804251115.pdf" }
      ]
    },
    {
      id: "madrasah",
      name: "বাংলাদেশ মাদ্রাসা শিক্ষা বোর্ড",
      shortName: "মাদ্রাসা",
      website: "https://www.bmeb.gov.bd",
      phone: "০২-৯৫৫০৩৫৩",
      email: "info@bmeb.gov.bd",
      address: "ঢাকা, বাংলাদেশ",
      established: "১৯৭৮",
      districts: ["সারা বাংলাদেশ"],
      pdfLinks: []
    },
    {
      id: "technical",
      name: "বাংলাদেশ কারিগরি শিক্ষা বোর্ড",
      shortName: "কারিগরি",
      website: "https://www.bteb.gov.bd",
      phone: "০২-৮৮৩৫৬৮৬",
      email: "info@bteb.gov.bd",
      address: "ঢাকা, বাংলাদেশ",
      established: "১৯৬৭",
      districts: ["সারা বাংলাদেশ"],
      pdfLinks: []
    }
  ],

  routines: [
    {
      id: 1,
      exam: "SSC পরীক্ষা ২০২৬",
      board: "ঢাকা, রাজশাহী, কুমিল্লা, যশোর, চট্টগ্রাম, বরিশাল, সিলেট, দিনাজপুর, ময়মনসিংহ",
      startDate: "2026-04-21",
      endDate: "2026-05-20",
      startDateDisplay: "২১ এপ্রিল ২০২৬",
      endDateDisplay: "২০ মে ২০২৬",
      practicalStartDate: "2026-06-07",
      practicalEndDate: "2026-06-14",
      practicalStartDisplay: "০৭ জুন ২০২৬",
      practicalEndDisplay: "১৪ জুন ২০২৬",
      pdfUrl: "https://dhakaeducationboard.gov.bd/data/20260115170804251115.pdf",
      link: "pages/ssc.html",
      year: "2026",
      schedule: [
        { date: "২১ এপ্রিল", subject: "বাংলা প্রথম পত্র" },
        { date: "২২ এপ্রিল", subject: "বাংলা দ্বিতীয় পত্র" },
        { date: "২৪ এপ্রিল", subject: "ইংরেজি প্রথম পত্র" },
        { date: "২৬ এপ্রিল", subject: "ইংরেজি দ্বিতীয় পত্র" },
        { date: "২৮ এপ্রিল", subject: "গণিত" },
        { date: "৩০ এপ্রিল", subject: "পদার্থ বিজ্ঞান / ব্যবসায় উদ্যোগ" },
        { date: "৩ মে", subject: "রসায়ন / হিসাববিজ্ঞান" },
        { date: "৫ মে", subject: "জীববিজ্ঞান / অর্থনীতি" },
        { date: "৭ মে", subject: "উচ্চতর গণিত / ফিন্যান্স ও ব্যাংকিং" },
        { date: "১০ মে", subject: "বাংলাদেশ ও বিশ্বপরিচয়" },
        { date: "১২ মে", subject: "তথ্য ও যোগাযোগ প্রযুক্তি" },
        { date: "১৪ মে", subject: "ধর্ম ও নৈতিক শিক্ষা" },
        { date: "১৭ মে", subject: "গার্হস্থ্য বিজ্ঞান / কৃষি শিক্ষা / সংগীত / চারু ও কারুকলা" },
        { date: "২০ মে", subject: "ভূগোল ও পরিবেশ / পৌরনীতি ও নাগরিকতা" },
        { date: "০৭-১৪ জুন", subject: "ব্যবহারিক পরীক্ষা (সকল বিষয়)" }
      ]
    },
    {
      id: 2,
      exam: "HSC পরীক্ষা ২০২৬",
      board: "সকল বোর্ড",
      startDate: "2026-04-02",
      endDate: "2026-05-18",
      startDateDisplay: "২ এপ্রিল ২০২৬",
      endDateDisplay: "১৮ মে ২০২৬",
      pdfUrl: "",
      link: "pages/hsc.html",
      year: "2026",
      schedule: [
        { date: "২ এপ্রিল", subject: "বাংলা প্রথম পত্র" },
        { date: "৩ এপ্রিল", subject: "বাংলা দ্বিতীয় পত্র" },
        { date: "৫ এপ্রিল", subject: "ইংরেজি প্রথম পত্র" },
        { date: "৬ এপ্রিল", subject: "ইংরেজি দ্বিতীয় পত্র" },
        { date: "৮ এপ্রিল", subject: "তথ্য ও যোগাযোগ প্রযুক্তি" },
        { date: "১০ এপ্রিল", subject: "পদার্থ বিজ্ঞান প্রথম পত্র / অর্থনীতি প্রথম পত্র" },
        { date: "১২ এপ্রিল", subject: "পদার্থ বিজ্ঞান দ্বিতীয় পত্র / অর্থনীতি দ্বিতীয় পত্র" },
        { date: "১৪ এপ্রিল", subject: "রসায়ন প্রথম পত্র / হিসাববিজ্ঞান প্রথম পত্র" },
        { date: "১৫ এপ্রিল", subject: "রসায়ন দ্বিতীয় পত্র / হিসাববিজ্ঞান দ্বিতীয় পত্র" },
        { date: "১৭ এপ্রিল", subject: "জীববিজ্ঞান প্রথম পত্র / ব্যবসায় সংগঠন প্রথম পত্র" },
        { date: "১৯ এপ্রিল", subject: "জীববিজ্ঞান দ্বিতীয় পত্র / ব্যবসায় সংগঠন দ্বিতীয় পত্র" },
        { date: "২২ এপ্রিল", subject: "উচ্চতর গণিত প্রথম পত্র / ফিন্যান্স ব্যাংকিং প্রথম পত্র" },
        { date: "২৬ এপ্রিল", subject: "উচ্চতর গণিত দ্বিতীয় পত্র / ফিন্যান্স ব্যাংকিং দ্বিতীয় পত্র" },
        { date: "২৯ এপ্রিল", subject: "ভূগোল প্রথম পত্র / মনোবিজ্ঞান প্রথম পত্র" },
        { date: "৩ মে", subject: "ইতিহাস প্রথম পত্র / সমাজকর্ম প্রথম পত্র" },
        { date: "৬ মে", subject: "ইসলামের ইতিহাস / কৃষিশিক্ষা প্রথম পত্র" },
        { date: "১৮ মে", subject: "ব্যবহারিক পরীক্ষা (শেষ দিন)" }
      ]
    },
    {
      id: 3,
      exam: "দাখিল পরীক্ষা ২০২৬",
      board: "মাদ্রাসা বোর্ড",
      startDate: "2026-02-15",
      endDate: "2026-03-12",
      startDateDisplay: "১৫ ফেব্রুয়ারি ২০২৬",
      endDateDisplay: "১২ মার্চ ২০২৬",
      pdfUrl: "",
      link: "pages/routines.html",
      year: "2026",
      schedule: [
        { date: "১৫ ফেব্রুয়ারি", subject: "কোরআন মজিদ ও তাজবিদ" },
        { date: "১৬ ফেব্রুয়ারি", subject: "আকাইদ ও ফিকহ" },
        { date: "১৮ ফেব্রুয়ারি", subject: "আরবি প্রথম পত্র" },
        { date: "১৯ ফেব্রুয়ারি", subject: "আরবি দ্বিতীয় পত্র" },
        { date: "২১ ফেব্রুয়ারি", subject: "বাংলা প্রথম পত্র" },
        { date: "২৩ ফেব্রুয়ারি", subject: "গণিত" },
        { date: "২৫ ফেব্রুয়ারি", subject: "ইংরেজি প্রথম পত্র" }
      ]
    }
  ],

  governmentNotices: [
    {
      id: 1,
      title: "২০২৫ সালের (৭ম-১০ম) শ্রেণির বোর্ড পরিবর্তনকৃত শিক্ষার্থীদের ছাড়পত্রের অনুমতি পত্র (TN: 1021-1053)",
      source: "dhakaeducationboard.portal.gov.bd",
      sourceUrl: "https://dhakaeducationboard.portal.gov.bd/pages/notices/%E0%A7%A8%E0%A7%A6%E0%A7%A8%E0%A7%AB-%E0%A6%B8%E0%A6%BE%E0%A6%B2%E0%A7%87%E0%A6%B0-%E0%A7%AD%E0%A6%AE-%E0%A7%A7%E0%A7%A6%E0%A6%AE-%E0%A6%B6%E0%A7%8D%E0%A6%B0%E0%A7%87%E0%A6%A3%E0%A6%BF%E0%A6%B0-%E0%A6%AC%E0%A7%8B%E0%A6%B0%E0%A7%8D%E0%A6%A1-%E0%A6%AA%E0%A6%B0%E0%A6%BF%E0%A6%AC%E0%A6%B0%E0%A7%8D%E0%A6%A4%E0%A6%A8%E0%A6%95%E0%A7%83%E0%A6%A4-%E0%A6%B6%E0%A6%BF%E0%A6%95%E0%A7%8D%E0%A6%B7%E0%A6%BE%E0%A6%B0%E0%A7%8D%E0%A6%A5%E0%A7%80%E0%A6%A6%E0%A7%87%E0%A6%B0-e6edb0-6919990581fc96cef9e613d7",
      date: "২০২৫",
      year: "2025",
      description: "২০২৫ সালের ৭ম-১০ম শ্রেণির বোর্ড পরিবর্তনকৃত শিক্ষার্থীদের ছাড়পত্রের অনুমতি পত্র সংক্রান্ত বিজ্ঞপ্তি।"
    },
    {
      id: 2,
      title: "মাধ্যমিক ও উচ্চ শিক্ষা বিভাগের সর্বশেষ নোটিশ",
      source: "shed.gov.bd",
      sourceUrl: "https://shed.gov.bd/pages/notices",
      date: "২০২৬",
      year: "2026",
      description: "সরকারি শিক্ষা সংক্রান্ত সর্বশেষ বিজ্ঞপ্তি, আদেশ ও পরিপত্র।"
    },
    {
      id: 3,
      title: "সরকারি মেধা ও উপবৃত্তি সংক্রান্ত বিজ্ঞপ্তি",
      source: "shed.gov.bd",
      sourceUrl: "https://shed.gov.bd/pages/moedu-scholarships",
      date: "২০২৬",
      year: "2026",
      description: "মাধ্যমিক পর্যায়ের মেধা বৃত্তি ও উপবৃত্তি সংক্রান্ত সরকারি বিজ্ঞপ্তি।"
    },
    {
      id: 4,
      title: "DGME: মেডিকেল শিক্ষা সংক্রান্ত সর্বশেষ নোটিশ",
      source: "dgme.gov.bd",
      sourceUrl: "https://dgme.gov.bd/pages/notices",
      date: "২০২৬",
      year: "2026",
      description: "স্বাস্থ্য শিক্ষা অধিদপ্তর (DGME) কর্তৃক প্রকাশিত মেডিকেল ভর্তি ও শিক্ষা সংক্রান্ত সর্বশেষ নোটিশ।"
    },
    {
      id: 5,
      title: "জাতীয় বিশ্ববিদ্যালয়ের সর্বশেষ নোটিশ ও বিজ্ঞপ্তি",
      source: "nu.ac.bd",
      sourceUrl: "https://www.nu.ac.bd",
      date: "২০২৬",
      year: "2026",
      description: "জাতীয় বিশ্ববিদ্যালয়ের ভর্তি, পরীক্ষা ও ফলাফল সংক্রান্ত সর্বশেষ বিজ্ঞপ্তি।"
    },
    {
      id: 6,
      title: "ঢাকা শিক্ষা বোর্ডের সর্বশেষ নোটিশ",
      source: "dhakaeducationboard.portal.gov.bd",
      sourceUrl: "https://dhakaeducationboard.portal.gov.bd",
      date: "২০২৬",
      year: "2026",
      description: "ঢাকা শিক্ষা বোর্ড কর্তৃক প্রকাশিত SSC, HSC ও অন্যান্য পরীক্ষা সংক্রান্ত সর্বশেষ নোটিশ ও বিজ্ঞপ্তি।"
    }
  ],

  importantLinks: [
    { name: "সরকারি বৃত্তি তথ্য", url: "https://shed.gov.bd/pages/moedu-scholarships", icon: "🏛️" },
    { name: "সরকারি নোটিশ", url: "https://shed.gov.bd/pages/notices", icon: "📋" },
    { name: "শিক্ষা মন্ত্রণালয়", url: "https://moedu.gov.bd", icon: "🏛️" },
    { name: "UGC Bangladesh", url: "https://ugc.gov.bd", icon: "🎓" },
    { name: "Board Results", url: "https://eboardresults.com", icon: "📊" },
    { name: "শিক্ষক বাতায়ন", url: "https://teachers.gov.bd", icon: "👩‍🏫" },
    { name: "জাতীয় বিশ্ববিদ্যালয়", url: "https://www.nu.ac.bd", icon: "🏫" },
    { name: "শিক্ষা বোর্ড", url: "https://educationboard.gov.bd", icon: "🏢" },
    { name: "BANBEIS", url: "https://banbeis.gov.bd", icon: "📈" },
    { name: "মাদ্রাসা বোর্ড", url: "https://www.bmeb.gov.bd", icon: "📚" },
    { name: "কারিগরি বোর্ড", url: "https://www.bteb.gov.bd", icon: "🔧" }
  ],

  sampleResults: {
    passed: {
      name: "রাহমান আহমেদ",
      roll: "123456",
      registration: "2024567890",
      board: "ঢাকা",
      exam: "SSC",
      year: "2024",
      gpa: "5.00",
      grade: "A+",
      status: "পাস",
      subjects: [
        { name: "বাংলা", grade: "A+", gpa: "5.00" },
        { name: "ইংরেজি", grade: "A+", gpa: "5.00" },
        { name: "গণিত", grade: "A+", gpa: "5.00" },
        { name: "বিজ্ঞান", grade: "A+", gpa: "5.00" },
        { name: "সমাজ বিজ্ঞান", grade: "A+", gpa: "5.00" },
        { name: "ধর্ম", grade: "A+", gpa: "5.00" },
        { name: "তথ্য ও যোগাযোগ প্রযুক্তি", grade: "A+", gpa: "5.00" }
      ]
    },
    failed: {
      name: "করিম মিয়া",
      roll: "654321",
      registration: "2024098765",
      board: "রাজশাহী",
      exam: "HSC",
      year: "2024",
      gpa: "0.00",
      grade: "F",
      status: "ফেল",
      subjects: [
        { name: "বাংলা", grade: "B", gpa: "3.00" },
        { name: "ইংরেজি", grade: "F", gpa: "0.00" },
        { name: "গণিত", grade: "C", gpa: "2.00" }
      ]
    }
  }
};

// Make data available globally
if (typeof module !== 'undefined' && module.exports) {
  module.exports = eduData;
}
